cmake_minimum_required(VERSION 3.20.0)
find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(sensor_fair_queue_tests)
test_runner_generate(src/main.c)
target_include_directories(app PRIVATE stubs ../../../include ../../../src/bluetooth/gatt_services)
target_sources(app PRIVATE src/main.c ../../../src/bluetooth/gatt_services/sensor_fair_queue.c)
